---
title: "AE 18: Simulation-based inferencr recap"
date: "`2021-10-20`"
output: 
  html_document:
    theme: readable
---

```{r load-packages, include = FALSE }
library(tidyverse)
```

## Announcements

- Ed Discussion for today's class: https://edstem.org/us/courses/8027/discussion/747205

- [HW 04](https://sta199-fa21-003.netlify.app/hw/hw-04.html) **due Wed, Oct 27 at 11:59pm**
  - Released after class

- Team Feedback #1 **due Wed, Oct 27 at 11:59pm**
  - Check inbox for email from Teammates to fill out feedback
  - This feedback is just graded on completion 
  
- [Prepare Week 10](https://sta199-fa21-003.netlify.app/prepare/week-10.html)
  - Prep Quiz 05 due **Mon, Oct 25 at 1:45pm**


## Statistics experience

[Click here](https://sta199-fa21-003.netlify.app/hw/stats-experience.html) for instructions.  
  
  - Due Fri, Dec 3

### Upcoming events

**HackDuke Code for Good - October 23 - 24**

- Free event but registration required
- Go to [2021.hackduke.org](https://2021.hackduke.org/) for more information. 
 
 **Duke Datathon - November 6 - 7**

- [Click here](https://dukeml.org/datathon/) for more information 


## AE 18: Simulation-based infernce recap

- Go to the `ae-18-[GITHUB USERNAME]` rep in the GitHub course organization:  https://github.com/sta199-fa21-003

- Access the RStudio Docker containers at https://vm-manage.oit.duke.edu/containers

- See the [Lab 01 instructions](https://sta199-fa21-003.netlify.app/labs/lab-01-hello-r.html) for details on cloning the repo and starting a new project in RStudio. 

