---
title: "AE 05: Data wrangling I"
subtitle: "NYC Flights"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: readable
---

```{r load-packages, include = FALSE }
library(tidyverse)
```

## Announcements

- Professor Tackett's office hours are moved to **Fridays 10a - 11a** on Zoom beginning this week

- Lab 02 due **today at 11:59p** on Gradescope

- Prep Quiz 01 **due Wed, Sep 08 at 1:45p**

- Ed Discussion board for today's lecture: https://edstem.org/us/courses/8027/discussion/590101


- [Week 04](https://sta199-fa21-003.netlify.app/prepare/week-04.html) prepare

## Questions about Lab 02? 

## Lab 01 returned on Gradescope 

- Find solutions on Sakai
- [See Course Policies](https://sta199-fa21-003.netlify.app/syllabus/#course-policies) in syllabus for regrade request policy
- Regrade requests must be submitted by **Monday, September 13**

## Code chunk names

- Why we name code chunks 
- Don't include spaces in code chunk names!
  - `r emo::ji("frowning_face")` ```{r plot data}``` 
  - `r emo::ji("slightly_smiling_face")` ```{r plot-data}``` 

## Questions from the prepare assignment? 

## AE 05: NYC Flights

### Clone a repo + start a new project

- Go to the `ae-05-[GITHUB USERNAME]` rep in the GitHub course organization:  https://github.com/sta199-fa21-003

- Access the RStudio Docker containers at https://vm-manage.oit.duke.edu/containers

- See the [Lab 01 instructions](https://sta199-fa21-003.netlify.app/labs/lab-01-hello-r.html) for details on cloning the repo and starting a new project in RStudio. 


